In [17]:
import numpy as np
import re
import math
import random

In [8]:
def import_data():
    data = []
    with open('file-tsp.txt') as f:
        for line in f:
            cords = re.split('\s+', line)
            data.append([float(cords[0]),float(cords[1])])
    return data

data = import_data()

In [15]:
def dist(city1, city2):
    return math.sqrt((city1[0] - city2[0])**2 + (city1[1] - city1[1]))

3
5


In [11]:
distance_matrix = np.zeros((50,50))

for i, city1 in enumerate(data):
    for j, city2 in enumerate(data):
        distance_matrix[i,j] = dist(city1, city2)


In [12]:
print(distance_matrix)

[[ 0.      0.1785  0.4823 ... 18.1404 18.7142 18.8374]
 [ 0.1785  0.      0.3038 ... 17.9619 18.5357 18.6589]
 [ 0.4823  0.3038  0.     ... 17.6581 18.2319 18.3551]
 ...
 [18.1404 17.9619 17.6581 ...  0.      0.5738  0.697 ]
 [18.7142 18.5357 18.2319 ...  0.5738  0.      0.1232]
 [18.8374 18.6589 18.3551 ...  0.697   0.1232  0.    ]]


In [134]:
def fitness(sequence):
    total_distance = 0
    for i in range(1,len(sequence)):
        total_distance += distance_matrix[sequence[i], sequence[i-1]]

    # In the slides 1/total_distance is used, this often gives a very small floating number
    return total_distance

def tsp_crossover(parent1, parent2):
    cutoff = sorted(random.sample(range(1,len(parent1)), 2))

    middle_p1 = parent1[cutoff[0]:cutoff[1]]
    middle_p2 = parent2[cutoff[0]:cutoff[1]]

    complement_p1 = parent1.copy()
    complement_p2 = parent2.copy()

    for x in middle_p1:
        complement_p2.remove(x)

    for x in middle_p2:
        complement_p1.remove(x)
    
    cutoff_complement = len(parent1) - cutoff[0]

    child1 = complement_p2[cutoff_complement:] + middle_p1 + complement_p2[:cutoff_complement] 
    child2 = complement_p1[cutoff_complement:] + middle_p2 + complement_p1[:cutoff_complement]

    return child1, child2

def tsp_mutation(parent):
    i1, i2 = random.sample(range(len(parent)), 2)
    parent[i1], parent[i2] = parent[i2], parent[i1]
    return parent


tsp_crossover([3,5,7,2,1,6,4,8], [2,5,7,6,8,1,3,4])
tsp_mutation([1,2,3,4])

[1, 2, 4, 3]

In [140]:
N = 500
K = 2
mutation_rate = 0.01
generations = 1500

def TSP():
    # Create population
    population = []
    for _ in range(N):
        population.append(np.random.permutation(50).tolist())

    for _ in range(generations):
    # Tournament selection
        parents = []
        indexes = np.random.permutation(50)
        for x, y in zip(*[iter(indexes)]*2):
            fitness_x = fitness(population[x])
            fitness_y = fitness(population[y])
            parents.append(x) if fitness_x < fitness_y else parents.append(y)
        
        parents_1 = np.roll(np.array(parents), 1)

        new_population = []
        min_distance = 100000000

        for i in range(len(parents)):
            parent_1 = population[parents[i]]
            parent_2 = population[parents_1[i]]

            child1, child2 = tsp_crossover(parent_1, parent_2)
            
            elements = [(fitness(parent_1), parent_1), (fitness(parent_2), parent_2), (fitness(child1), child1), (fitness(child2), child2)]
            top_elements = sorted(elements)[:2]
            new_population.append(top_elements[0][1])
            new_population.append(top_elements[1][1])
            min_distance = min(min_distance, top_elements[0][0])

        # TODO add mutations

        population = new_population
        print(min_distance)
            



TSP()

254.32329999999993
232.15560000000005
232.15560000000005
225.91219999999998
219.43780000000004
213.90430000000003
208.094
183.82020000000003
183.82020000000003
148.11610000000005
148.11610000000005
148.11610000000005
137.78480000000002
137.78480000000002
135.9848
127.33229999999999
127.33229999999999
126.59850000000002
121.38170000000001
121.38170000000001
121.38170000000001
116.85100000000003
113.39380000000004
113.39380000000004
113.39380000000004
110.8234
106.60890000000003
106.60890000000003
95.16010000000003
95.16010000000003
90.84390000000002
90.84390000000002
90.84390000000002
88.75780000000003
88.75780000000003
88.17190000000002
88.17190000000002
83.2908
83.2908
83.2908
81.05799999999999
81.05799999999999
81.05799999999999
81.05799999999999
79.8948
79.08530000000002
77.8685
77.39800000000001
77.37390000000002
74.3195
74.3195
73.4345
71.891
71.891
71.891
71.66290000000001
71.66290000000001
69.3715
69.3715
68.71950000000001
68.22049999999999
68.22049999999999
67.7796
66.6602
66.6